#!/usr/bin/env zsh
echo "Installing dotfiles"
pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo $folder
    stow -D $folder
    stow $folder
done
popd
echo "Completed installation"
