#!/usr/bin/env zsh
if [[ -z $STOW_FOLDERS ]]; then
    # STOW_FOLDERS="bin,netflix,nvim,personal,tmux,uwuntu,xkb,zsh" from Primeagen
    STOW_FOLDERS="bin,gh,nvim,tmux,zsh"
    echo "Setting stow folders variable: $STOW_FOLDERS"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
    echo "Setting dotfiles variable: $DOTFILES"
fi

export STOW_FOLDERS=$STOW_FOLDERS
export DOTFILES=$DOTFILES
$DOTFILES/install
